// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaEnsino.API.Data;

#nullable disable

namespace Sistema_Academico_Integrado.Migrations
{
    [DbContext(typeof(PlataformaContext))]
    [Migration("20260828123048_AdicionarImagemUrlCurso")]
    partial class AdicionarImagemUrlCurso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlataformaEnsino.API.Models.AlternativaQuestaoBanco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhCorreta")
                        .HasColumnType("bit");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("QuestaoBancoId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoBancoId", "Letra")
                        .IsUnique();

                    b.ToTable("AlternativasQuestoesBanco");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.AlternativaQuestaoPublicada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhCorreta")
                        .HasColumnType("bit");

                    b.Property<string>("JustificativaSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("QuestaoPublicadaId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoPublicadaId", "Letra")
                        .IsUnique();

                    b.ToTable("AlternativasQuestoesPublicadas");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.AnexoQuestaoBanco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("QuestaoBancoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoAnexo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoBancoId");

                    b.ToTable("AnexosQuestoesBanco");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<decimal>("NotaMaxima")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("PesoNota")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("PesoProgresso")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("ProfessorAutorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusPublicacao")
                        .HasColumnType("int");

                    b.Property<int?>("TempoLimiteMinutos")
                        .HasColumnType("int");

                    b.Property<int>("TentativasPermitidas")
                        .HasColumnType("int");

                    b.Property<int>("TipoAvaliacao")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("ProfessorAutorId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.ConteudoDidatico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorpoTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoProgresso")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("ProfessorAutorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusPublicacao")
                        .HasColumnType("int");

                    b.Property<int>("TipoConteudo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("ProfessorAutorId");

                    b.HasIndex("TurmaId");

                    b.ToTable("ConteudosDidaticos");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoRegistro")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("CoordenadorId")
                        .HasColumnType("int");

                    b.Property<int>("CriadoPor")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoRegistro")
                        .IsUnique();

                    b.HasIndex("CoordenadorId");

                    b.HasIndex("CriadoPor");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.FeedbackAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<bool>("Lido")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("DestinatarioId", "CriadoEm");

                    b.ToTable("FeedbacksAcademicos");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.LancamentoNotaAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvaliacaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackProfessor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LiberadaAoAlunoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<decimal>("NotaOficial")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("OrigemCorrecao")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoNota")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("ProfessorResponsavelId")
                        .HasColumnType("int");

                    b.Property<int?>("TentativaAvaliacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.HasIndex("ModuloId");

                    b.HasIndex("ProfessorResponsavelId");

                    b.HasIndex("TentativaAvaliacaoId");

                    b.HasIndex("MatriculaId", "AvaliacaoId")
                        .IsUnique();

                    b.ToTable("LancamentosNotasAlunos");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.MarcoProgressoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("Escopo")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeradoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int");

                    b.Property<int?>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Origem")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentualMarco")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("ModuloId");

                    b.HasIndex("MatriculaId", "Escopo", "CursoId", "ModuloId", "PercentualMarco");

                    b.ToTable("MarcosProgressosAlunos");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoRegistro")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NotaFinal")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("CodigoRegistro")
                        .IsUnique();

                    b.HasIndex("CursoId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoRegistro")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoRegistro")
                        .IsUnique();

                    b.HasIndex("CursoId", "Titulo")
                        .IsUnique();

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.ProgressoConteudoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConteudoDidaticoId")
                        .HasColumnType("int");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentualConclusao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("PrimeiroAcessoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusProgresso")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConteudoDidaticoId");

                    b.HasIndex("ModuloId");

                    b.HasIndex("MatriculaId", "ConteudoDidaticoId")
                        .IsUnique();

                    b.ToTable("ProgressosConteudosAlunos");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.ProgressoCursoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int");

                    b.Property<decimal>("MediaCurso")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("ModulosConcluidos")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentualConclusao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PesoConcluido")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("PesoTotal")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("StatusProgresso")
                        .HasColumnType("int");

                    b.Property<int>("TotalModulos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("MatriculaId", "CursoId")
                        .IsUnique();

                    b.ToTable("ProgressosCursosAlunos");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.ProgressoModuloAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvaliacoesConcluidas")
                        .HasColumnType("int");

                    b.Property<int>("ConteudosConcluidos")
                        .HasColumnType("int");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int");

                    b.Property<decimal>("MediaModulo")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentualConclusao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PesoConcluido")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("PesoTotal")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("StatusProgresso")
                        .HasColumnType("int");

                    b.Property<int>("TotalAvaliacoes")
                        .HasColumnType("int");

                    b.Property<int>("TotalConteudos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("MatriculaId", "ModuloId")
                        .IsUnique();

                    b.ToTable("ProgressosModulosAlunos");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.QuestaoBanco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Dificuldade")
                        .HasColumnType("tinyint");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExplicacaoPosResposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfessorAutorId")
                        .HasColumnType("int");

                    b.Property<string>("Subtema")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TipoQuestao")
                        .HasColumnType("int");

                    b.Property<string>("TituloInterno")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorAutorId");

                    b.ToTable("QuestoesBanco");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.QuestaoPublicada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliacaoId")
                        .HasColumnType("int");

                    b.Property<string>("ContextoSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnunciadoSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExplicacaoSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal>("Pontos")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("QuestaoBancoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoQuestao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoBancoId");

                    b.HasIndex("AvaliacaoId", "Ordem")
                        .IsUnique();

                    b.ToTable("QuestoesPublicadas");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.RespostaAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlternativaQuestaoPublicadaId")
                        .HasColumnType("int");

                    b.Property<bool?>("Correta")
                        .HasColumnType("bit");

                    b.Property<decimal>("PontosObtidos")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("QuestaoPublicadaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RespondidaEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("RespostaTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TentativaAvaliacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlternativaQuestaoPublicadaId");

                    b.HasIndex("QuestaoPublicadaId");

                    b.HasIndex("TentativaAvaliacaoId", "QuestaoPublicadaId")
                        .IsUnique();

                    b.ToTable("RespostasAlunos");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.TentativaAvaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliacaoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CorrigidaEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnviadaEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IniciadaEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int");

                    b.Property<decimal>("NotaBruta")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("NumeroTentativa")
                        .HasColumnType("int");

                    b.Property<int>("StatusTentativa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.HasIndex("MatriculaId", "AvaliacaoId", "NumeroTentativa")
                        .IsUnique();

                    b.ToTable("TentativasAvaliacao");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoRegistro")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeTurma")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoRegistro")
                        .IsUnique();

                    b.HasIndex("CursoId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("NomeTurma", "CursoId")
                        .IsUnique();

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Admin", b =>
                {
                    b.HasBaseType("PlataformaEnsino.API.Models.Usuario");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Aluno", b =>
                {
                    b.HasBaseType("PlataformaEnsino.API.Models.Usuario");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Coordenador", b =>
                {
                    b.HasBaseType("PlataformaEnsino.API.Models.Usuario");

                    b.Property<string>("CodigoRegistro")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasIndex("CodigoRegistro")
                        .IsUnique()
                        .HasFilter("[CodigoRegistro] IS NOT NULL");

                    b.ToTable("Coordenadores", (string)null);
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Professor", b =>
                {
                    b.HasBaseType("PlataformaEnsino.API.Models.Usuario");

                    b.Property<string>("CodigoRegistro")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasIndex("CodigoRegistro")
                        .IsUnique()
                        .HasFilter("[CodigoRegistro] IS NOT NULL");

                    b.ToTable("Professores", (string)null);
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.AlternativaQuestaoBanco", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.QuestaoBanco", "QuestaoBanco")
                        .WithMany("Alternativas")
                        .HasForeignKey("QuestaoBancoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestaoBanco");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.AlternativaQuestaoPublicada", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.QuestaoPublicada", "QuestaoPublicada")
                        .WithMany("Alternativas")
                        .HasForeignKey("QuestaoPublicadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestaoPublicada");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.AnexoQuestaoBanco", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.QuestaoBanco", "QuestaoBanco")
                        .WithMany("Anexos")
                        .HasForeignKey("QuestaoBancoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestaoBanco");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Avaliacao", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Modulo", "Modulo")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Professor", "ProfessorAutor")
                        .WithMany("AvaliacoesPublicadas")
                        .HasForeignKey("ProfessorAutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Turma", "Turma")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("ProfessorAutor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.ConteudoDidatico", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Modulo", "Modulo")
                        .WithMany("ConteudosDidaticos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Professor", "ProfessorAutor")
                        .WithMany("ConteudosDidaticos")
                        .HasForeignKey("ProfessorAutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Turma", "Turma")
                        .WithMany("ConteudosDidaticos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("ProfessorAutor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Curso", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Coordenador", "Coordenador")
                        .WithMany()
                        .HasForeignKey("CoordenadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlataformaEnsino.API.Models.Admin", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coordenador");

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.FeedbackAcademico", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Usuario", "Autor")
                        .WithMany("FeedbacksEnviados")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlataformaEnsino.API.Models.Usuario", "Destinatario")
                        .WithMany("FeedbacksRecebidos")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Destinatario");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.LancamentoNotaAluno", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Avaliacao", "Avaliacao")
                        .WithMany("LancamentosNota")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Matricula", "Matricula")
                        .WithMany("LancamentosNota")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Modulo", "Modulo")
                        .WithMany("LancamentosNota")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Professor", "ProfessorResponsavel")
                        .WithMany("LancamentosNota")
                        .HasForeignKey("ProfessorResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlataformaEnsino.API.Models.TentativaAvaliacao", "TentativaAvaliacao")
                        .WithMany()
                        .HasForeignKey("TentativaAvaliacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Avaliacao");

                    b.Navigation("Matricula");

                    b.Navigation("Modulo");

                    b.Navigation("ProfessorResponsavel");

                    b.Navigation("TentativaAvaliacao");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.MarcoProgressoAluno", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Curso", "Curso")
                        .WithMany("MarcosProgresso")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Matricula", "Matricula")
                        .WithMany("MarcosProgresso")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Modulo", "Modulo")
                        .WithMany("MarcosProgresso")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Curso");

                    b.Navigation("Matricula");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Matricula", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Aluno", "Aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Turma", "Turma")
                        .WithMany("Matriculas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aluno");

                    b.Navigation("Curso");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Modulo", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Curso", "Curso")
                        .WithMany("Modulos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.ProgressoConteudoAluno", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.ConteudoDidatico", "ConteudoDidatico")
                        .WithMany("ProgressosAlunos")
                        .HasForeignKey("ConteudoDidaticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Matricula", "Matricula")
                        .WithMany("ProgressosConteudo")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Modulo", "Modulo")
                        .WithMany("ProgressosConteudo")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConteudoDidatico");

                    b.Navigation("Matricula");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.ProgressoCursoAluno", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Curso", "Curso")
                        .WithMany("ProgressosAlunos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Matricula", "Matricula")
                        .WithMany("ProgressosCurso")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.ProgressoModuloAluno", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Matricula", "Matricula")
                        .WithMany("ProgressosModulo")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Modulo", "Modulo")
                        .WithMany("ProgressosAlunos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matricula");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.QuestaoBanco", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Professor", "ProfessorAutor")
                        .WithMany("QuestoesBanco")
                        .HasForeignKey("ProfessorAutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProfessorAutor");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.QuestaoPublicada", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Avaliacao", "Avaliacao")
                        .WithMany("Questoes")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.QuestaoBanco", "QuestaoBanco")
                        .WithMany("QuestoesPublicadas")
                        .HasForeignKey("QuestaoBancoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Avaliacao");

                    b.Navigation("QuestaoBanco");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.RespostaAluno", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.AlternativaQuestaoPublicada", "AlternativaQuestaoPublicada")
                        .WithMany()
                        .HasForeignKey("AlternativaQuestaoPublicadaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlataformaEnsino.API.Models.QuestaoPublicada", "QuestaoPublicada")
                        .WithMany("Respostas")
                        .HasForeignKey("QuestaoPublicadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.TentativaAvaliacao", "TentativaAvaliacao")
                        .WithMany("Respostas")
                        .HasForeignKey("TentativaAvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternativaQuestaoPublicada");

                    b.Navigation("QuestaoPublicada");

                    b.Navigation("TentativaAvaliacao");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.TentativaAvaliacao", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Avaliacao", "Avaliacao")
                        .WithMany("Tentativas")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Matricula", "Matricula")
                        .WithMany("TentativasAvaliacao")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Avaliacao");

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Turma", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Curso", "Curso")
                        .WithMany("Turmas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaEnsino.API.Models.Professor", "ProfessorResponsavel")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("ProfessorResponsavel");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Admin", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("PlataformaEnsino.API.Models.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Aluno", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("PlataformaEnsino.API.Models.Aluno", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Coordenador", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("PlataformaEnsino.API.Models.Coordenador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Professor", b =>
                {
                    b.HasOne("PlataformaEnsino.API.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("PlataformaEnsino.API.Models.Professor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Avaliacao", b =>
                {
                    b.Navigation("LancamentosNota");

                    b.Navigation("Questoes");

                    b.Navigation("Tentativas");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.ConteudoDidatico", b =>
                {
                    b.Navigation("ProgressosAlunos");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Curso", b =>
                {
                    b.Navigation("MarcosProgresso");

                    b.Navigation("Modulos");

                    b.Navigation("ProgressosAlunos");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Matricula", b =>
                {
                    b.Navigation("LancamentosNota");

                    b.Navigation("MarcosProgresso");

                    b.Navigation("ProgressosConteudo");

                    b.Navigation("ProgressosCurso");

                    b.Navigation("ProgressosModulo");

                    b.Navigation("TentativasAvaliacao");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Modulo", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("ConteudosDidaticos");

                    b.Navigation("LancamentosNota");

                    b.Navigation("MarcosProgresso");

                    b.Navigation("ProgressosAlunos");

                    b.Navigation("ProgressosConteudo");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.QuestaoBanco", b =>
                {
                    b.Navigation("Alternativas");

                    b.Navigation("Anexos");

                    b.Navigation("QuestoesPublicadas");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.QuestaoPublicada", b =>
                {
                    b.Navigation("Alternativas");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.TentativaAvaliacao", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Turma", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("ConteudosDidaticos");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Usuario", b =>
                {
                    b.Navigation("FeedbacksEnviados");

                    b.Navigation("FeedbacksRecebidos");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Aluno", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("PlataformaEnsino.API.Models.Professor", b =>
                {
                    b.Navigation("AvaliacoesPublicadas");

                    b.Navigation("ConteudosDidaticos");

                    b.Navigation("LancamentosNota");

                    b.Navigation("QuestoesBanco");
                });
#pragma warning restore 612, 618
        }
    }
}
